### ISSUE TITLE
MGCB und Projekt bauen in verschiedene Verzeichnisse?!

### ISSUE THREAD

**Issue by Didddy** [thegritsch/Schlosskirsch#2]
https://github.com/thegritsch/Schlosskirsch/blob/1be4f44997e13f57dbcf9d319c6d25f5a626b973/Schlosskirsch/Content/Content.mgcb#L4

Irgendwie check i's net... der MGCB Editor baut net in den gleichen Ordner wie die .exe... kopierst du die dann immer händisch zur .exe? Oder gibt's da einen versteckten Automatismus?

**Comment by thegritsch** [comment]
Das hat sich anscheinend mit Monogame 3.8 geändert. Der Content wird jetzt über den BuilderTask gebaut. https://docs.monogame.net/articles/migrate_37.html 
Hab versuchsweise ein neues Templateprojekt erstellt und den Inhalt kopiert, das Problem ist jetzt dass die GeonBit.UI library kein .net core 3.1 unterstützt.

**Comment by Didddy** [comment]
Ah, ok, das wird's sein... Project-File updaten wär eh gut.

Hmm, ob GeonBit hochgezogen wird? Das letzte Release von denen is scho ziemlich lang her... zumindest .NET Standard 2.0 sollte aber gehen.
